// <auto-generated />
using System;
using FamilyApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyApplication.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221129210742_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FamilyApplication.Models.CalendarEntry", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecurrenceInDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("CalendarId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CalendarEntries");
                });

            modelBuilder.Entity("FamilyApplication.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("dbb27d61-f494-4e80-82ad-0186e35c2515"),
                            CategoryName = "Abby"
                        },
                        new
                        {
                            CategoryId = new Guid("6fadd7c7-d24a-4e43-a411-06b9844c6c9f"),
                            CategoryName = "Familie"
                        },
                        new
                        {
                            CategoryId = new Guid("7a2a8355-d33a-4267-9da6-2d4877920d07"),
                            CategoryName = "Sabina"
                        },
                        new
                        {
                            CategoryId = new Guid("a561cd97-3b2e-40c1-b9c2-e7aea68460e7"),
                            CategoryName = "Darius"
                        });
                });

            modelBuilder.Entity("FamilyApplication.Models.CalendarEntry", b =>
                {
                    b.HasOne("FamilyApplication.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
